### ISSUE TITLE
Baseline scoring for Testing Team

### ISSUE THREAD

**Issue by oneNutW0nder** [scorestack/scorestack#157]
**What do you want ScoreStack to do that it cannot currently do?**
For a _testing_ team (team 14 ISTS) we should have a feature that allows for `automatic passing` of a check for that team. This way we can get a _max score_ at the end of a period of time instead of calculating manually.

**Comment by s-newman** [comment]
Dynamicbeat will always index a result for all checks it runs. Therefore, this can be easily determined by running a `_count` query against a results index and optionally filtering for `passed:true` to determine the current score or the total possible score for a team.

This baseline scoring may only be needed if Dynamicbeat is shown to index a different number of check results for each team. This has not happened, and if it does happen that would probably be a bug that should be solved in a different way.
