### ISSUE TITLE
Deployment looping

### ISSUE THREAD

**Issue by mcutshaw** [scorestack/scorestack#259]
**Describe the bug**
Setup appears to loop with the setup container never being able to properly authenticate with kibana.

**To Reproduce**
1. Follow deployment for a small -> docker setup.

**Expected behavior**
I expect the setup process to not appear to loop infinitely. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11272312/97830609-c587ad80-1c8a-11eb-8dae-f083be59d619.png)

**Comment by mcutshaw** [comment]
Leaving it as user error for the moment

**Comment by oneNutW0nder** [comment]
Please note, when deploying the _small docker setup_, watch the _setup_ container logs and wait for it to exit. The looping behavior being described is caused when Kibana is being waited on to finish its setup.
