### ISSUE TITLE
Segfault on invalid check

### ISSUE THREAD

**Issue by s-newman** [scorestack/scorestack#305]
Bug Report
----------

If Dynamicbeat tries to unpack a check that doesn't define one of the required metadata settings, it will segfault.

### Expected behavior

Dynamicbeat should gracefully handle invalid checks by printing an error and moving on.

### Actual behavior

Dynamicbeat crashed due to a segfault, which made it difficult to find the offending check.

### Replication steps

1. Deploy a Scorestack instance
2. Add a check without one of the required settings (id, name, type, group, score_weight)
3. Run Dynamicbeat against the Scorestack instance

### Screenshots

<img width="1200" alt="Screen Shot 2021-03-23 at 10 43 45 PM" src="https://user-images.githubusercontent.com/25960951/112246548-3ffc9e00-8c29-11eb-9a03-68296b933e8f.png">

**Comment by P0nt14c** [comment]
Motion to close due to Mav fixing issue last spring.
